// This is only using for unit tests because the combined runtime code compiles faster.

#include "il2c.c"
#include "System.Object.c"
#include "System.ValueType.c"
#include "System.Char.c"
#include "System.String.c"
#include "System.Boolean.c"
#include "System.Byte.c"
#include "System.Int16.c"
#include "System.Int32.c"
#include "System.Int64.c"
#include "System.SByte.c"
#include "System.UInt16.c"
#include "System.UInt32.c"
#include "System.UInt64.c"
#include "System.IntPtr.c"
#include "System.UIntPtr.c"
#include "System.Single.c"
#include "System.Double.c"
